import React from 'react';

const App: React.FC = () => {
  return (
    <div className="min-h-screen bg-white text-gray-900 flex flex-col items-center justify-center p-4">
      <h1 className="text-4xl font-bold mb-4">Welcome to the Landing Page</h1>
      <p className="text-lg text-gray-700">This page is currently using a light theme.</p>
      <p className="text-sm text-gray-500 mt-2">Generated by AI IDE</p>
    </div>
  );
};

export default App;
